namespace Meridian.Mcp;

public static class MeridianMcpMessages
{
    public const string StaleGraphNote = "This graph is precomputed. If source code changes, MCP results will not reflect those changes until meridian scan is run again and the running MCP server is reloaded with reload_graph or restarted.";

    public const string EndpointAnalyzerLimit = "No ASP.NET Core endpoint nodes are present in this graph. The graph may be stale, generated by an older Meridian version, from a non-web project, or using an unsupported endpoint pattern.";

    public static string TruncationNote(int limit)
    {
        return $"TRUNCATED: Limit of {limit} results reached. Use get_node or narrower query_graph filters to drill down.";
    }
}
